#Had to write my own findSDL2 as it was playing up on windows.

message("finding sdl2")
FIND_PATH(SDL2_INCLUDE_DIRS SDL.h
    PATHS ${SDL2_ROOT}/include
        ENV SDL2_ROOT
    PATH_SUFFIXES include/)

set(SDL2_LIBRARIES "" CACHE STRING "" FORCE)

FIND_LIBRARY(SDL2_MAIN_LIB NAMES SDL2main
    PATHS ${SDL2_ROOT}/lib/x64
    PATH_SUFFIXES a lib
    )

FIND_LIBRARY(SDL2_LIB NAMES SDL2
    PATHS ${SDL2_ROOT}/lib/x64
    PATH_SUFFIXES a lib
    )

IF(WIN32)
    FIND_FILE(SDL2_DLL SDL2.dll
        PATH_SUFFIXES ${SDL2_ROOT}/lib/x64
        )
endif()

if(SDL2_MAIN_LIB)
  set(SDL2_LIBRARIES "${SDL2_MAIN_LIB};${SDL2_LIB}" CACHE STRING "" FORCE)
endif()
message("${SDL2_ROOT}/lib/x64")
message("FOUND: ${SDL2_LIB}")
message("FOUND: ${SDL2_LIBRARIES}")

SET(SDL2_FOUND FALSE)
IF(SDL2_INCLUDE_DIRS AND SDL2_LIBRARIES)
   SET(SDL2_FOUND TRUE)
ENDIF(SDL2_INCLUDE_DIRS AND SDL2_LIBRARIES)

IF(SDL2_FOUND)
   IF (NOT SDL2_FIND_QUIETLY)
       MESSAGE(STATUS "Found SDL2: ${SDL2_LIBRARIES}")
       MESSAGE(STATUS "Found SDL2 includes: ${SDL2_INCLUDE_DIRS}")
   ENDIF (NOT SDL2_FIND_QUIETLY)
ELSE(SDL2_FOUND)
   IF (SDL2_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find SDL2")
   ENDIF (SDL2_FIND_REQUIRED)
ENDIF(SDL2_FOUND)

mark_as_advanced( FORCE
    SDL2_INCLUDE_DIRS
)