name: Build Android

on:
  push:
    branches: ['android']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
      - name: Set lowercase build type
        run: echo "BUILD_TYPE_LOWER=$(echo '${{ matrix.buildType }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout avEngine-android
        uses: actions/checkout@v4
        with:
          repository: OtherMythos/avEngine-android
          path: avEngine-android

      - name: Replace avEngine submodule with this version
        run: |
          rm -rf avEngine-android/app/src/main/avEngine

      - name: Checkout engine
        uses: actions/checkout@v4
        with:
          path: avEngine-android/app/src/main/avEngine

      - name: Download prebuilt Android dependencies
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltAndroid-${{ matrix.buildType }}.tar.gz
          repo: OtherMythos/avBuild
          workflow: android.yml

      - name: Extract dependencies
        run: |
          mkdir deps
          tar -xvf android-avBuilt-${{ matrix.buildType }}.tar.gz -C deps
          echo "Extracted to deps"

      - name: Set up Java and Android SDK
        uses: android-actions/setup-android@v3

      - name: Download Android NDK r25
        run: |
          curl -L -o ndk.zip https://dl.google.com/android/repository/android-ndk-r25-linux.zip
          unzip -q ndk.zip
          mv android-ndk-r25 ~/ndk

      - name: Set local.properties
        run: echo "ndk.dir=/home/runner/ndk" >> avEngine-android/local.properties

      - name: Set JAVA_HOME explicitly (needed for some gradle builds)
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Run setup.py
        working-directory: avEngine-android
        run: |
          python3 setup.py ${{ github.workspace }}/deps/${{ matrix.buildType }}/

      - name: Build APK
        working-directory: avEngine-android
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: avEngine-android-${{ matrix.buildType }}.apk
          path: avEngine-android/app/build/outputs/apk/${{env.BUILD_TYPE_LOWER}}/app-${{env.BUILD_TYPE_LOWER}}.apk
