name: Build Linux

on:
  push:
    branches:  'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltLinux.tar.gz
          repo: OtherMythos/avBuild
          workflow: linux.yml
      - name: Expand artifact
        run: |
          tar -xvf avBuiltLinux.tar.gz
      - name: Setup CMake
        run: |
          mkdir build
          cd build
          cmake -DAV_LIBS_DIR="${{ github.workspace }}/avBuilt/Debug" -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        run: |
          cd build
          cmake --build . --target av