name: Build Windows

on:
  push:
    branches:  'master'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: avBuiltWindows.zip
            repository: OtherMythos/avBuild
            path: ~/
