name: Build Windows

on:
  push:
    branches:  'master'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltWindows.zip
          repo: OtherMythos/avBuild
          workflow: windows.yml
      - name: Expand artifact
        run: |
          Expand-Archive avBuilt-windows.zip .
      - name: Setup CMake
        run: |
          mkdir build
          cd build
          cmake -DAV_LIBS_DIR="${{ github.workspace }}/avBuilt/Debug" -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        run: |
          cd build
          cmake --build . --target av
          ls Debug