name: Build Linux

on:
  push:
    branches:  'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          sudo apt-get update && sudo apt-get install -y libxaw7-dev libxrandr-dev libxcb-randr0-dev libx11-dev xserver-xorg-dev xorg-dev libx11-xcb1 libxcb-res0-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libgtk-3-dev
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: avBuiltLinux.tar.gz
          repo: OtherMythos/avBuild
          workflow: linux.yml
      - name: Expand artifact
        run: |
          tar -xvf build.tar.gz
      - name: Setup CMake
        run: |
          mkdir build
          cd build
          cmake -DAV_LIBS_DIR="${{ github.workspace }}/Debug" -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        run: |
          cd build
          cmake --build . --target av